services:
  fernando01:
    container_name: fernando01
    image: localhost:5555/karavan/fernando01:d932e7a
    networks:
    - karavan
    ports:
    - 8086:8080
    restart: always
    volumes:
    - "/home/devel1/karavan-tests/inbox:/var/karavan/inbox"    
    - "/home/devel1/karavan-tests/outbox:/var/karavan/outbox"   
